server:
  port: 8080

spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=GMT
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        #连接池的补充设置
        #初始化大小，最小，最大
        initialSize: 5
        minIdle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        # 校验SQL，Oracle配置 spring.datasource.validationQuery=SELECT 1 FROM DUAL，如果不配validationQuery项，则下面三项配置无用
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize : 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙,wall开启会导致flyway初始化失败错误：sql注入，操作不被允许执行
        filters: stat
        connectionProperties : druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

    # 使用Redis统一管理Session可以实现单点登录
    redis:
      host: 127.0.0.1
      port: 6379
      password : demo
      timeout: 0
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  # 全局异常处理：抛出后会被GlobalExceptionHandler.class处理
    mvc:
      #出现错误时, 直接抛出异常
      throw-exception-if-no-handler-found: true
#    resources:
#      add-mappings: false


#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

project:
  version: 1.0.0
  author: 李灿峰
  createDate: 2019-03-13

# 日志配置
logback:
  logdir: D:/idea/log
  .appname: demo



