#执行java -jar xxx.jar，可以观察到服务端口被设置为8001，也就是默认的开发环境（dev）
#执行java -jar xxx.jar --spring.profiles.active=test，可以观察到服务端口被设置为8002，也就是测试环境的配置（test）
#执行java -jar xxx.jar --spring.profiles.active=prod，可以观察到服务端口被设置为8003，也就是生产环境的配置（prod）
#如果不指定，则默认加载application.yml的配置
spring:
    profiles:
      active: dev


